// Auto-generated icon loader - DO NOT EDIT MANUALLY
// Generated by: npm run icons:integrate
// Regenerate after adding new icons

import { ImageSourcePropType } from 'react-native';
import { MaterialType } from '../config/materials';

// Stone icon imports
import amphibolite from '../../assets/icons/stones/amphibolite.png';
import andesite from '../../assets/icons/stones/andesite.png';
import basalt from '../../assets/icons/stones/basalt.png';
import chalk from '../../assets/icons/stones/chalk.png';
import chert from '../../assets/icons/stones/chert.png';
import clay from '../../assets/icons/stones/clay.png';
import conglomerate from '../../assets/icons/stones/conglomerate.png';
import diabase from '../../assets/icons/stones/diabase.png';
import diorite from '../../assets/icons/stones/diorite.png';
import dolomite from '../../assets/icons/stones/dolomite.png';
import flint from '../../assets/icons/stones/flint.png';
import gabbro from '../../assets/icons/stones/gabbro.png';
import gneiss from '../../assets/icons/stones/gneiss.png';
import granite from '../../assets/icons/stones/granite.png';
import greenstone from '../../assets/icons/stones/greenstone.png';
import hematite from '../../assets/icons/stones/hematite.png';
import limestone from '../../assets/icons/stones/limestone.png';
import magnetite from '../../assets/icons/stones/magnetite.png';
import malachite from '../../assets/icons/stones/malachite.png';
import marble from '../../assets/icons/stones/marble.png';
import mudstone from '../../assets/icons/stones/mudstone.png';
import obsidian from '../../assets/icons/stones/obsidian.png';
import pegmatite from '../../assets/icons/stones/pegmatite.png';
import phyllite from '../../assets/icons/stones/phyllite.png';
import quartzite from '../../assets/icons/stones/quartzite.png';
import rhyolite from '../../assets/icons/stones/rhyolite.png';
import sandstone from '../../assets/icons/stones/sandstone.png';
import schist from '../../assets/icons/stones/schist.png';
import serpentinite from '../../assets/icons/stones/serpentinite.png';
import shale from '../../assets/icons/stones/shale.png';
import siltstone from '../../assets/icons/stones/siltstone.png';
import slate from '../../assets/icons/stones/slate.png';
import soapstone from '../../assets/icons/stones/soapstone.png';
import travertine from '../../assets/icons/stones/travertine.png';
import tuff from '../../assets/icons/stones/tuff.png';

// Wood icon imports
import african_acacia from '../../assets/icons/woods/african_acacia.png';
import african_ebony from '../../assets/icons/woods/african_ebony.png';
import african_juniper from '../../assets/icons/woods/african_juniper.png';
import african_mahogany from '../../assets/icons/woods/african_mahogany.png';
import african_olive from '../../assets/icons/woods/african_olive.png';
import aleppo_pine from '../../assets/icons/woods/aleppo_pine.png';
import american_beech from '../../assets/icons/woods/american_beech.png';
import american_hickory from '../../assets/icons/woods/american_hickory.png';
import american_oak from '../../assets/icons/woods/american_oak.png';
import asian_bamboo from '../../assets/icons/woods/asian_bamboo.png';
import balsa from '../../assets/icons/woods/balsa.png';
import balsam_fir from '../../assets/icons/woods/balsam_fir.png';
import banyan from '../../assets/icons/woods/banyan.png';
import baobab from '../../assets/icons/woods/baobab.png';
import black_walnut from '../../assets/icons/woods/black_walnut.png';
import blackwood from '../../assets/icons/woods/blackwood.png';
import brazil_nut from '../../assets/icons/woods/brazil_nut.png';
import brazilian_rosewood from '../../assets/icons/woods/brazilian_rosewood.png';
import burmese_teak from '../../assets/icons/woods/burmese_teak.png';
import ceiba from '../../assets/icons/woods/ceiba.png';
import coast_redwood from '../../assets/icons/woods/coast_redwood.png';
import coconut_palm from '../../assets/icons/woods/coconut_palm.png';
import cork_oak from '../../assets/icons/woods/cork_oak.png';
import dipterocarp from '../../assets/icons/woods/dipterocarp.png';
import douglas_fir from '../../assets/icons/woods/douglas_fir.png';
import eastern_white_pine from '../../assets/icons/woods/eastern_white_pine.png';
import eucalyptus from '../../assets/icons/woods/eucalyptus.png';
import european_ash from '../../assets/icons/woods/european_ash.png';
import european_beech from '../../assets/icons/woods/european_beech.png';
import european_larch from '../../assets/icons/woods/european_larch.png';
import european_oak from '../../assets/icons/woods/european_oak.png';
import guadua_bamboo from '../../assets/icons/woods/guadua_bamboo.png';
import huon_pine from '../../assets/icons/woods/huon_pine.png';
import indian_rosewood from '../../assets/icons/woods/indian_rosewood.png';
import iroko from '../../assets/icons/woods/iroko.png';
import jacaranda from '../../assets/icons/woods/jacaranda.png';
import jarrah from '../../assets/icons/woods/jarrah.png';
import kauri from '../../assets/icons/woods/kauri.png';
import mahogany from '../../assets/icons/woods/mahogany.png';
import mangrove from '../../assets/icons/woods/mangrove.png';
import manuka from '../../assets/icons/woods/manuka.png';
import marula from '../../assets/icons/woods/marula.png';
import mesquite from '../../assets/icons/woods/mesquite.png';
import neem from '../../assets/icons/woods/neem.png';
import norway_spruce from '../../assets/icons/woods/norway_spruce.png';
import nz_beech from '../../assets/icons/woods/nz_beech.png';
import obeche from '../../assets/icons/woods/obeche.png';
import olive from '../../assets/icons/woods/olive.png';
import palm from '../../assets/icons/woods/palm.png';
import paper_birch from '../../assets/icons/woods/paper_birch.png';
import parana_pine from '../../assets/icons/woods/parana_pine.png';
import poplar from '../../assets/icons/woods/poplar.png';
import quebracho from '../../assets/icons/woods/quebracho.png';
import rimu from '../../assets/icons/woods/rimu.png';
import rubber_tree from '../../assets/icons/woods/rubber_tree.png';
import sal from '../../assets/icons/woods/sal.png';
import sandalwood from '../../assets/icons/woods/sandalwood.png';
import scots_pine from '../../assets/icons/woods/scots_pine.png';
import siberian_cedar from '../../assets/icons/woods/siberian_cedar.png';
import siberian_larch from '../../assets/icons/woods/siberian_larch.png';
import silver_birch from '../../assets/icons/woods/silver_birch.png';
import sugar_maple from '../../assets/icons/woods/sugar_maple.png';
import teak from '../../assets/icons/woods/teak.png';
import wenge from '../../assets/icons/woods/wenge.png';
import western_red_cedar from '../../assets/icons/woods/western_red_cedar.png';
import willow from '../../assets/icons/woods/willow.png';

// Food icon imports
import acai from '../../assets/icons/foods/acai.png';
import acorn from '../../assets/icons/foods/acorn.png';
import aguaje from '../../assets/icons/foods/aguaje.png';
import amaranth_greens from '../../assets/icons/foods/amaranth_greens.png';
import baobab_fruit from '../../assets/icons/foods/baobab_fruit.png';
import bilberry from '../../assets/icons/foods/bilberry.png';
import blackthorn_sloe from '../../assets/icons/foods/blackthorn_sloe.png';
import blueberry from '../../assets/icons/foods/blueberry.png';
import brazil_nut_food from '../../assets/icons/foods/brazil_nut_food.png';
import bush_mango from '../../assets/icons/foods/bush_mango.png';
import bush_tomato from '../../assets/icons/foods/bush_tomato.png';
import camu_camu from '../../assets/icons/foods/camu_camu.png';
import cashew_fruit from '../../assets/icons/foods/cashew_fruit.png';
import cherimoya from '../../assets/icons/foods/cherimoya.png';
import chickweed from '../../assets/icons/foods/chickweed.png';
import cocona from '../../assets/icons/foods/cocona.png';
import coconut from '../../assets/icons/foods/coconut.png';
import cranberry from '../../assets/icons/foods/cranberry.png';
import cupuacu from '../../assets/icons/foods/cupuacu.png';
import davidson_plum from '../../assets/icons/foods/davidson_plum.png';
import dragon_fruit from '../../assets/icons/foods/dragon_fruit.png';
import durian from '../../assets/icons/foods/durian.png';
import elderberry from '../../assets/icons/foods/elderberry.png';
import elderberry_ne from '../../assets/icons/foods/elderberry_ne.png';
import finger_lime from '../../assets/icons/foods/finger_lime.png';
import guava from '../../assets/icons/foods/guava.png';
import hazelnut from '../../assets/icons/foods/hazelnut.png';
import hickory_nut from '../../assets/icons/foods/hickory_nut.png';
import jackfruit from '../../assets/icons/foods/jackfruit.png';
import kakadu_plum from '../../assets/icons/foods/kakadu_plum.png';
import lingonberry from '../../assets/icons/foods/lingonberry.png';
import longan from '../../assets/icons/foods/longan.png';
import lychee from '../../assets/icons/foods/lychee.png';
import macadamia from '../../assets/icons/foods/macadamia.png';
import mangosteen from '../../assets/icons/foods/mangosteen.png';
import marula_fruit from '../../assets/icons/foods/marula_fruit.png';
import moringa from '../../assets/icons/foods/moringa.png';
import muntries from '../../assets/icons/foods/muntries.png';
import natal_plum from '../../assets/icons/foods/natal_plum.png';
import passion_fruit from '../../assets/icons/foods/passion_fruit.png';
import pawpaw from '../../assets/icons/foods/pawpaw.png';
import persimmon from '../../assets/icons/foods/persimmon.png';
import quandong from '../../assets/icons/foods/quandong.png';
import rambutan from '../../assets/icons/foods/rambutan.png';
import rosehip from '../../assets/icons/foods/rosehip.png';
import serviceberry from '../../assets/icons/foods/serviceberry.png';
import shea_nut from '../../assets/icons/foods/shea_nut.png';
import stinging_nettle from '../../assets/icons/foods/stinging_nettle.png';
import tamarind from '../../assets/icons/foods/tamarind.png';
import wild_banana from '../../assets/icons/foods/wild_banana.png';
import wild_fig_af from '../../assets/icons/foods/wild_fig_af.png';
import wild_garlic from '../../assets/icons/foods/wild_garlic.png';
import wild_grape from '../../assets/icons/foods/wild_grape.png';
import wild_strawberry_ne from '../../assets/icons/foods/wild_strawberry_ne.png';
import wild_strawberry_pa from '../../assets/icons/foods/wild_strawberry_pa.png';

// Stone icons
const STONE_ICONS: Record<string, ImageSourcePropType> = {
  amphibolite,
  andesite,
  basalt,
  chalk,
  chert,
  clay,
  conglomerate,
  diabase,
  diorite,
  dolomite,
  flint,
  gabbro,
  gneiss,
  granite,
  greenstone,
  hematite,
  limestone,
  magnetite,
  malachite,
  marble,
  mudstone,
  obsidian,
  pegmatite,
  phyllite,
  quartzite,
  rhyolite,
  sandstone,
  schist,
  serpentinite,
  shale,
  siltstone,
  slate,
  soapstone,
  travertine,
  tuff,
};

// Wood icons
const WOOD_ICONS: Record<string, ImageSourcePropType> = {
  african_acacia,
  african_ebony,
  african_juniper,
  african_mahogany,
  african_olive,
  aleppo_pine,
  american_beech,
  american_hickory,
  american_oak,
  asian_bamboo,
  balsa,
  balsam_fir,
  banyan,
  baobab,
  black_walnut,
  blackwood,
  brazil_nut,
  brazilian_rosewood,
  burmese_teak,
  ceiba,
  coast_redwood,
  coconut_palm,
  cork_oak,
  dipterocarp,
  douglas_fir,
  eastern_white_pine,
  eucalyptus,
  european_ash,
  european_beech,
  european_larch,
  european_oak,
  guadua_bamboo,
  huon_pine,
  indian_rosewood,
  iroko,
  jacaranda,
  jarrah,
  kauri,
  mahogany,
  mangrove,
  manuka,
  marula,
  mesquite,
  neem,
  norway_spruce,
  nz_beech,
  obeche,
  olive,
  palm,
  paper_birch,
  parana_pine,
  poplar,
  quebracho,
  rimu,
  rubber_tree,
  sal,
  sandalwood,
  scots_pine,
  siberian_cedar,
  siberian_larch,
  silver_birch,
  sugar_maple,
  teak,
  wenge,
  western_red_cedar,
  willow,
};

// Food icons
const FOOD_ICONS: Record<string, ImageSourcePropType> = {
  acai,
  acorn,
  aguaje,
  amaranth_greens,
  baobab_fruit,
  bilberry,
  blackthorn_sloe,
  blueberry,
  brazil_nut_food,
  bush_mango,
  bush_tomato,
  camu_camu,
  cashew_fruit,
  cherimoya,
  chickweed,
  cocona,
  coconut,
  cranberry,
  cupuacu,
  davidson_plum,
  dragon_fruit,
  durian,
  elderberry,
  elderberry_ne,
  finger_lime,
  guava,
  hazelnut,
  hickory_nut,
  jackfruit,
  kakadu_plum,
  lingonberry,
  longan,
  lychee,
  macadamia,
  mangosteen,
  marula_fruit,
  moringa,
  muntries,
  natal_plum,
  passion_fruit,
  pawpaw,
  persimmon,
  quandong,
  rambutan,
  rosehip,
  serviceberry,
  shea_nut,
  stinging_nettle,
  tamarind,
  wild_banana,
  wild_fig_af,
  wild_garlic,
  wild_grape,
  wild_strawberry_ne,
  wild_strawberry_pa,
};

// Map material types to icon maps
const ICON_MAPS: Partial<Record<MaterialType, Record<string, ImageSourcePropType>>> = {
  stone: STONE_ICONS,
  wood: WOOD_ICONS,
  food: FOOD_ICONS,
};

/**
 * Get the icon for a resource.
 * Returns the import result for use with Image source prop, or null if no icon exists.
 */
export function getResourceIcon(
  type: MaterialType,
  resourceId: string
): ImageSourcePropType | null {
  const iconMap = ICON_MAPS[type];
  if (!iconMap) {
    return null;
  }
  return iconMap[resourceId] ?? null;
}

/**
 * Check if a resource has an icon.
 */
export function hasResourceIcon(type: MaterialType, resourceId: string): boolean {
  return getResourceIcon(type, resourceId) !== null;
}

/**
 * Get counts of available icons.
 */
export function getIconCounts(): { stones: number; woods: number; foods: number; total: number } {
  const stones = Object.keys(STONE_ICONS).length;
  const woods = Object.keys(WOOD_ICONS).length;
  const foods = Object.keys(FOOD_ICONS).length;
  return {
    stones,
    woods,
    foods,
    total: stones + woods + foods,
  };
}
